-- Заполнение справочника операторов/приложений
-- Данные взяты из файла операторыпродавцыиприложения-2.txt

INSERT INTO operators (pattern, app_name, is_p2p) VALUES
('NBU 2P2 U PLAT UZCARD, 99', 'Milliy 2.0', true),
('NBU P2P HUMO UZCARD>', 'Milliy 2.0', true),
('NBU P2P HUMOHUMO>tas', 'Milliy 2.0', true),
('NBU P2P UZCARD HUMO, 99', 'Milliy 2.0', true),
('PSP P2P AKSIYA>TASHK', 'MyUztelecom', true),
('PSP P2P AKSIYA, UZ', 'MyUztelecom', true),
('PSP P2P HUMO2UZCARD>', 'MyUztelecom', true),
('UPAY P2P', 'Humans', true),
('UPAY P2P, UZ', 'Humans', true),
('UPAY Humo2Uzcard>TOS', 'Humans', true),
('UPAY UZCARD2HUMO, UZ', 'Humans', true),
('UPAY HUMO2HUMO P2P>T', 'Humans', true),
('DAVR UPAY HUMANS UZCARD2UZCARD, UZ', 'Humans', true),
('DAVR UPAY HUMANS UZCARD2HU, UZ', 'Humans', true),
('TENGE UNIVERSAL P2P, UZ', 'Tenge24', true),
('T24 P2P Humo to Uzca', 'Tenge24', true),
('NEW DBO UZKART-HUMO, UZ', 'Tenge24', true),
('TENGE 24 P2P UZCARD UZCARD, UZ', 'Tenge24', true),
('TENGE 24 P2P UZCARD HUMO, UZ', 'Tenge24', true),
('Tenge24 P2P UZCARDHU', 'Tenge24', true),
('TENGE-24 WS P2P INTERBANK, UZ', 'Tenge24', true),
('TENGE-24 WS P2P INTERBANK SPISANIYE UZCA, UZ', 'Tenge24', true),
('TENGE-24 WS P2P U2H-E, UZ', 'Tenge24', true),
('TENGE24 WS P2P H2UEW', 'Tenge24', true),
('XAZNA OTHERS 2 ANY, 99', 'Xazna', true),
('XAZNA OTHERS TO HUMO, 99', 'Xazna', true),
('XAZNA HUMO 2 UZCARD', 'Xazna', true),
('XAZNA P2P>TOSHKENT', 'Xazna', true),
('DAVR MOBILE UZCARD UZCARD, UZ', 'Davr Mobile', true),
('DAVR MOBILE P2P H2U>', 'Davr Mobile', true),
('DAVR MOBILE P2P H2H>', 'Davr Mobile', true),
('DAVR MOBILE HUMO UZCARD, UZ', 'Davr Mobile', true),
('DAVR MOBILE P2P KOMIS, UZ', 'Davr Mobile', true),
('DAVR MOBILE UZCARD HUMO, UZ', 'Davr Mobile', true),
('HAMKORBANK ATB, UZ', 'Hamkor', true),
('HAMKOR P2P UZKARD>AN', 'Hamkor', true),
('HAMKOR HUMO P2P>Andi', 'Hamkor', true),
('OQ P2P, UZ', 'OQ', true),
('OQ P2P>TASHKENT', 'OQ', true),
('TOSHKENT SH., AT KHALK BANKI BOSH AMALIY, 99', 'Paynet', true),
('UZPAYNET>Shayxontoxu', 'Paynet', true),
('PAYNET HUM2UZC NEW>T', 'Paynet', true),
('UZPAYNET>Toshkent Sh', 'Paynet', true),
('UZCARD OTHERS 2 ANY PAYNET, 99', 'Paynet', true),
('PAYNET P2P HUM2UZC>S', 'Paynet', true),
('XAZNA PAYNET TOLOV>T', 'Xazna', true),
('TOSHKENT SH., MIKROKREDITBANK ATB BOSH, UZ', 'Mavrid', true),
('MKBANK MAVRID UZCARD', 'Mavrid', true),
('MKBANK P2P UZCARD MAVRID, UZ', 'Mavrid', true),
('UZCARD PLYUS P2P, 99', 'Joyda', true),
('UZCARD PLYUS P2P HUMO BOSHQA BANK, 99', 'Joyda', true),
('UZCARD P2P, UZ', 'Agrobank', true),
('ASAKABANK HUMO UZCAR', 'Asakabank', true),
('TOSHKENT SH., ASAKA AT BANKINING BOSH, 99', 'Asakabank', true),
('ASAKABANK UZCARD HUMO P2P BB, 99', 'Asakabank', true),
('ASAKA HUMO UZCARD P2', 'Asakabank', true),
('SMARTBANK P2P O2O UZCARD, UZ', 'SmartBank', true),
('SMARTBANK UZCARD HUMO P2P, UZ', 'SmartBank', true),
('SmartBank P2P UZCARD', 'SmartBank', true),
('SmartBank P2P HUMO U', 'SmartBank', true),
('SmartBank P2P O2O HU', 'SmartBank', true),
('BEEPUL UZCARD 2 UZCARD, UZ', 'Beepul', true),
('BEEPUL UZCARD 2 HUMO, UZ', 'Beepul', true),
('PAYWAY 05, UZ', 'PayWay', true),
('PAYME P2P, UZ', 'Payme', true),
('PAYME OPLATA, UZ', 'Payme', false),
('UB PEREVOD CROSSBORDER 6 SEND, UZ', 'UzumBank', true),
('SQB MOBILE UZCARD P2P UZCARD, UZ', 'SQB', true),
('SQB MOBILE HUMO P2P', 'SQB', true),
('CHAKANAPAY UZCARD TOUZCARD, UZ', 'Chakanapay', true),
('ChakanaPay Humo to Uzcard', 'Chakanapay', true),
('ChakanaPay Humo Uzca', 'Chakanapay', true),
('TBC HUMO P2P>TASHKEN', 'TBC', true),
('NBU ONLINE KONVERSIY', 'Milliy 2.0', false),
('PL HUMANS OPLATA>TOS', 'Humans', false)
ON CONFLICT (pattern) DO NOTHING;

UPDATE operators
SET canonical_name = pattern
WHERE canonical_name IS NULL;
